---DROP ALL TABLES TO MAKE SURE THE SCHEMA IS CLEAR
DROP TABLE PROFILE CASCADE CONSTRAINTS;
DROP TABLE FRIENDS CASCADE CONSTRAINTS;
DROP TABLE PENDINGFRIENDS CASCADE CONSTRAINTS;
DROP TABLE GROUPS CASCADE CONSTRAINTS;
DROP TABLE GROUPMEMBERSHIP CASCADE CONSTRAINTS;
DROP TABLE PENDINGGROUPMEMBERS CASCADE CONSTRAINTS;
DROP TABLE MESSAGES CASCADE CONSTRAINTS;
DROP TABLE MESSAGERECIPIENT CASCADE CONSTRAINTS;

---CREATING PROFILE TABLE
CREATE TABLE PROFILE(
userID          varchar2(20)    not null deferrable,
name            varchar2(50)    not null deferrable,
email           varchar2(50)    not null deferrable,
password        varchar2(50 )   not null deferrable,
date_of_birth   date,
lastlogin       timestamp,
CONSTRAINT PROFILE_PK PRIMARY KEY (userID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT PROFILE_UN UNIQUE(email) INITIALLY IMMEDIATE DEFERRABLE
); 

---CREATING FRIENDS TABLE
CREATE TABLE FRIENDS(
userID1     varchar2(20)    not null deferrable,
userID2     varchar2(20)    not null deferrable,
JDate       date            not null deferrable,
message     varchar2(200),
CONSTRAINT FRIENDS_PK PRIMARY KEY (userID1, userID2) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT FRIENDS_FK1 FOREIGN KEY (userID1) REFERENCES PROFILE(userID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT FRIENDS_FK2 FOREIGN KEY (userID2) REFERENCES PROFILE(userID) INITIALLY IMMEDIATE DEFERRABLE
);

---CREATING PENDINGFRIENDS TABLE
CREATE TABLE PENDINGFRIENDS(
fromID      varchar2(20)    not null deferrable,
toID        varchar2(20)    not null deferrable,
message     varchar2(200),
CONSTRAINT PENDINGFRIENDS_PK PRIMARY KEY (fromID, toID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT PENDINGFRIENDS_FK1 FOREIGN KEY (fromID) REFERENCES PROFILE(userID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT PENDINGFRIENDS_FK2 FOREIGN KEY (toID) REFERENCES PROFILE(userID) INITIALLY IMMEDIATE DEFERRABLE
); 

---CREATING GROUPS TABLE
CREATE TABLE GROUPS(
gID           varchar2(20)    not null deferrable,
name          varchar2(50)    not null deferrable,
description   varchar2(200),
CONSTRAINT GROUPS_PK PRIMARY KEY (gID) INITIALLY IMMEDIATE DEFERRABLE
);

---CREATING GROUPMEMBERSHIP TABLE
CREATE TABLE GROUPMEMBERSHIP(
gID         varchar2(20)    not null deferrable,
userID      varchar2(50),
role        varchar2(20),
CONSTRAINT GROUPMEMBERSHIP_PK PRIMARY KEY (gID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT GROUPMEMBERSHIP_FK1 FOREIGN KEY (gID) REFERENCES GROUPS(gID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT GROUPMEMBERSHIP_FK2 FOREIGN KEY (userID) REFERENCES PROFILE(userID) INITIALLY IMMEDIATE DEFERRABLE
);

---CREATING PENDINGGROUPMEMBERS TABLE
CREATE TABLE PENDINGGROUPMEMBERS(
gID         varchar2(20)    not null deferrable,
userID      varchar2(20)    not null deferrable,
message     varchar2(200),
CONSTRAINT PENDINGGROUPMEMBERS_PK PRIMARY KEY (gID, userID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT PENDINGGROUPMEMBERS_FK1 FOREIGN KEY (gID) REFERENCES GROUPS(gID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT PENDINGGROUPMEMBERS_FK2 FOREIGN KEY (userID) REFERENCES PROFILE(userID) INITIALLY IMMEDIATE DEFERRABLE
);

---CREATING MESSAGES TABLE
CREATE TABLE MESSAGES(
msgID       varchar2(20)    not null deferrable,
fromID      varchar2(20),  
message     varchar2(200),
toUserID    varchar2(20)    default null,
toGroupID   varchar2(20)    default null,
dateSent    date            not null deferrable,
CONSTRAINT MESSAGES_PK PRIMARY KEY (msgID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT MESSAGES_FK1 FOREIGN KEY (fromID) REFERENCES PROFILE(userID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT MESSAGES_FK2 FOREIGN KEY (toUserID) REFERENCES PROFILE(userID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT MESSAGES_FK3 FOREIGN KEY (toGroupID) REFERENCES GROUPS(gID) INITIALLY IMMEDIATE DEFERRABLE
);

---CREATING MESSAGERECIPIENT TABLE
CREATE TABLE MESSAGERECIPIENT(
msgID       varchar2(20)     not null deferrable,
userID      varchar2(20),
CONSTRAINT MESSAGERECIPIENT_PK PRIMARY KEY (msgID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT MESSAGERECIPIENT_FK1 FOREIGN KEY (userID) REFERENCES PROFILE(userID) INITIALLY IMMEDIATE DEFERRABLE,
CONSTRAINT MESSAGERECIPIENT_FK2 FOREIGN KEY (msgID) REFERENCES MESSAGES(msgID) INITIALLY IMMEDIATE DEFERRABLE
);